# Generated by Django 2.2.12 on 2022-07-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220708_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=30, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(max_length=15, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(max_length=10, verbose_name='Пол'),
        ),
    ]
