# Generated by Django 2.2.12 on 2022-07-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220708_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.CharField(max_length=2, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='person',
            name='interest',
            field=models.CharField(max_length=35, null=True, verbose_name='Увлечение'),
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='person',
            name='town',
            field=models.CharField(max_length=30, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(max_length=20, null=True, verbose_name='Имя пользователя'),
        ),
    ]
