# Generated by Django 2.2.12 on 2022-07-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220708_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.CharField(max_length=30, null=True, verbose_name='User_id')),
            ],
        ),
        migrations.CreateModel(
            name='User_Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.CharField(max_length=30, null=True, verbose_name='User_id')),
            ],
        ),
    ]
