# Generated by Django 2.2.12 on 2022-07-09 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_log_person_user_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Login',
        ),
    ]
