# Generated by Django 2.2.12 on 2022-07-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220709_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, null=True, verbose_name='User_id')),
            ],
        ),
    ]
