# Generated by Django 2.2.12 on 2022-07-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_log_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='online',
            field=models.BooleanField(default=False, verbose_name='Session status'),
        ),
        migrations.AddField(
            model_name='person',
            name='token',
            field=models.CharField(max_length=200, null=True, verbose_name='Token session'),
        ),
    ]
