# Generated by Django 2.2.12 on 2022-07-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20220710_0425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30, null=True, verbose_name='User_id')),
                ('interest', models.CharField(max_length=35, null=True, verbose_name='Увлечение')),
                ('town', models.CharField(max_length=30, null=True, verbose_name='Город')),
            ],
        ),
    ]
