# Generated by Django 2.2.12 on 2022-07-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Пол')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('town', models.CharField(max_length=30, verbose_name='Город')),
                ('interest', models.CharField(max_length=35, verbose_name='Увлечение')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('email', models.CharField(max_length=30, verbose_name='E-mail')),
                ('password', models.CharField(max_length=15, verbose_name='Password')),
            ],
        ),
    ]
