# Generated by Django 2.2.12 on 2022-07-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_auto_20220707_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Office',
        ),
    ]
